server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      group-id: food-delivery-group
    producer:
      bootstrap-servers: localhost:9092

